# Generated by Django 3.0.6 on 2020-05-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('one_hour_cost', models.IntegerField()),
                ('two_hour_cost', models.IntegerField()),
                ('three_hour_cost', models.IntegerField()),
                ('four_hour_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('max_profit', models.IntegerField()),
                ('ticket_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('one_hour_cost', models.IntegerField()),
                ('two_hour_cost', models.IntegerField()),
                ('three_hour_cost', models.IntegerField()),
                ('four_hour_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordDebl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('song_cost_record', models.IntegerField()),
                ('song_cost_rehearsal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('one_hour_cost', models.IntegerField()),
                ('two_hour_cost', models.IntegerField()),
                ('three_hour_cost', models.IntegerField()),
                ('four_hour_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_clip_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='Enter name of city', max_length=100)),
                ('population', models.IntegerField(help_text='Enter population of the city')),
                ('fans_need', models.IntegerField(help_text='Enter number of fans to open city')),
                ('fastfood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Fastfood')),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Gig')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Hospital')),
                ('pub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Pub')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.RecordingStudio')),
                ('strip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Strip')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.RecordDebl')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.VideoClip')),
            ],
        ),
    ]
