# Generated by Django 3.0.6 on 2020-05-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200522_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('one_hour_cost', models.IntegerField()),
                ('two_hour_cost', models.IntegerField()),
                ('three_hour_cost', models.IntegerField()),
                ('four_hour_cost', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Dealer'),
        ),
    ]
