# Generated by Django 3.0.6 on 2020-05-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200525_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='max_profit',
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='video_clip_cost',
        ),
        migrations.AddField(
            model_name='dealer',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='min_bandrating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pub',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recordingstudio',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recordingstudio',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='recordingstudio',
            name='min_bandrating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingstudio',
            name='studio_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strip',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='studio_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='four_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='one_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='three_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='two_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='four_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='one_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='three_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='two_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='four_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='one_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='three_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='two_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordingstudio',
            name='song_cost_record',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordingstudio',
            name='song_cost_rehearsal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strip',
            name='four_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strip',
            name='one_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strip',
            name='three_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strip',
            name='two_hour_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecordDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('record_rank', models.CharField(blank=True, max_length=3, null=True)),
                ('min_bandrating', models.IntegerField(blank=True, null=True)),
                ('min_fans', models.IntegerField(blank=True, null=True)),
                ('min_albums', models.IntegerField(blank=True, null=True)),
                ('min_albumrating', models.IntegerField(blank=True, null=True)),
                ('distribution_power', models.IntegerField(blank=True, null=True)),
                ('revenue_share', models.IntegerField(blank=True, null=True)),
                ('album_type', models.CharField(blank=True, max_length=100, null=True)),
                ('studio_discount', models.IntegerField(blank=True, null=True)),
                ('videoclip_discount', models.IntegerField(blank=True, null=True)),
                ('videoclip_count', models.IntegerField(blank=True, null=True)),
                ('upfront_money', models.IntegerField(blank=True, null=True)),
                ('revenue_affect', models.IntegerField(blank=True, null=True)),
                ('songs_required', models.IntegerField(blank=True, null=True)),
                ('songs_minimum_rating', models.IntegerField(blank=True, null=True)),
                ('videoclips_required', models.IntegerField(blank=True, null=True)),
                ('gigs_required', models.IntegerField(blank=True, null=True)),
                ('fine_amount', models.IntegerField(blank=True, null=True)),
                ('cancel_cooldown', models.IntegerField(blank=True, null=True)),
                ('due_date', models.IntegerField(blank=True, null=True)),
                ('gigs_locations', models.ManyToManyField(to='about.Gig')),
                ('studio_locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.RecordingStudio')),
                ('videoclip_locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.VideoClip')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.RecordDeal'),
        ),
        migrations.DeleteModel(
            name='RecordDebl',
        ),
    ]
