# Generated by Django 3.0.6 on 2020-05-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200525_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='min_bandrating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
