# Generated by Django 3.0.6 on 2020-06-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20200601_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
