# Generated by Django 3.0.6 on 2020-06-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20200602_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
