# Generated by Django 3.0.6 on 2020-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
