# Generated by Django 3.0.6 on 2020-06-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_index_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='city',
            name='dealer_x',
        ),
        migrations.RemoveField(
            model_name='city',
            name='dealer_y',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
