# Generated by Django 3.0.6 on 2020-06-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20200615_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddeal',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorddeal',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingstudio',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingstudio',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
